VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use the same key for each machine
  # config.ssh.insert_key = false

  config.vm.define "master" do |master|
    master.vm.box = "generic/ubuntu2010"
    master.vm.hostname = "master"
    config.vm.network "public_network", ip: "192.168.1.50", :bridge => "en1: Intel(R) Dual Band Wireless-AC 8260"
    master.vm.provision "file", source: "id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
    public_key = File.read("id_rsa.pub")
    master.vm.provision :shell, :inline =>"
        echo 'Copying ansible-vm public SSH Keys to the VM'
        mkdir -p /home/vagrant/.ssh
        chmod 700 /home/vagrant/.ssh
        echo '#{public_key}' >> /home/vagrant/.ssh/authorized_keys
        chmod -R 600 /home/vagrant/.ssh/authorized_keys
        echo 'Host 192.168.*.*' >> /home/vagrant/.ssh/config
        echo 'StrictHostKeyChecking no' >> /home/vagrant/.ssh/config
        echo 'UserKnownHostsFile /dev/null' >> /home/vagrant/.ssh/config
        chmod -R 600 /home/vagrant/.ssh/config
        chmod 400 /home/vagrant/.ssh/id_rsa
        sudo apt install ansible -y
        ", privileged: false   
    master.vm.provider "virtualbox" do |vbmaster|
      vbmaster.name = "ansible_master"
    end
  end

  config.vm.define "web" do |web|
    web.vm.box = "generic/ubuntu2010"
    web.vm.hostname = "web"
    config.vm.network "public_network", ip: "192.168.1.51", :bridge => "en1: Intel(R) Dual Band Wireless-AC 8260"
    web.vm.provision "file", source: "id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
    public_key = File.read("id_rsa.pub")
    web.vm.provision :shell, :inline =>"
        echo 'Copying ansible-vm public SSH Keys to the VM'
        mkdir -p /home/vagrant/.ssh
        chmod 700 /home/vagrant/.ssh
        echo '#{public_key}' >> /home/vagrant/.ssh/authorized_keys
        chmod -R 600 /home/vagrant/.ssh/authorized_keys
        echo 'Host 192.168.*.*' >> /home/vagrant/.ssh/config
        echo 'StrictHostKeyChecking no' >> /home/vagrant/.ssh/config
        echo 'UserKnownHostsFile /dev/null' >> /home/vagrant/.ssh/config
        chmod -R 600 /home/vagrant/.ssh/config
        chmod 400 /home/vagrant/.ssh/id_rsa
        ", privileged: false
    web.vm.provider "virtualbox" do |vbweb|
      vbweb.name = "ansible_web"
    end
  end  
end
